### ISSUE TITLE
Build Debian package for release

### ISSUE THREAD

**Issue by qwandor-google** [alsuren/mijia-homie#18]
It would be useful to build Debian packages for Raspberry Pi (and maybe other targets) that users can install rather than building from source.

**Comment by qwandor** [comment]
Once cargo-deb is sorted, https://www.reddit.com/r/rust/comments/ht0p25/github_actions_for_packaging_deb_rpm_statically/ or https://github.com/NLnetLabs/krill/blob/master/.github/workflows/pkg.yml#L56 may be useful for figuring out how to get cross-compilation working with Github Actions.

**Comment by qwandor** [comment]
Next steps: trigger the package workflow when mijia-home-* tag is pushed, if the packaging is successful then [create a draft release](https://github.com/marketplace/actions/create-a-release) and add the Debian packages to it. When release is (manually) published, push them to the repository.

**Comment by qwandor** [comment]
Remaining things to do:
 - [ ] Generate a suitable GPG keypair and enable signing on https://bintray.com/alsuren/mijia-homie.
 - [ ] Fill in the description and other details on https://bintray.com/alsuren/mijia-homie.

**Comment by qwandor** [comment]
Moved to https://bintray.com/homie-rs/homie-rs instead, and filled in details there.
