### ISSUE TITLE
controller: properties sometimes have no payload if not updated at runtime

### ISSUE THREAD

**Issue by afflux** [alsuren/mijia-homie#227]
Core issue is this:
https://github.com/alsuren/mijia-homie/blob/e7e0229e7890371838c2b3795e99e7d5a82ee7fb/homie-controller/src/lib.rs#L514-L516

I have a node that updates very rarely. After restart of the controller, my broker publishes the retained payload topic before the node's $properties attribute, causing those payloads to get lost.

I'd suggest not to subscribe to wildcards, instead subscribe explicitly to the attributes, then to the payloads as discovered.

**Comment by qwandor** [comment]
I've pushed `homie-controller` 0.7.0 to crates.io with your fix for this.
