### ISSUE TITLE
Homie to InfluxDB exporter

### ISSUE THREAD

**Issue by alsuren** [alsuren/mijia-homie#34]
Might be best to set up a local development environment for influxdb+grafana first.

* pick an influxdb library 
  * https://github.com/lautis/ruuvitag-listener just uses the line format

* build it as an example in homie-controller for now

(I also found this in my travels: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/mqtt_consumer )

**Comment by qwandor-google** [comment]
https://crates.io/crates/influx_db_client seems to be the most popular and maintained crate for InfluxDB.

**Comment by qwandor** [comment]
There are some stability issues to fix still, but it is released and working so closing this issue.
