### ISSUE TITLE
rename publish-mqtt to mijia-publisher

### ISSUE THREAD

**Issue by alsuren** [alsuren/mijia-homie#36]
* move the directory
* update run.sh etc
* kill off the old .service files on the raspberry pis
* Update the names on https://alsuren.github.io/mijia-homie/doc/presentation/#10

**Comment by qwandor** [comment]
Or maybe `mijia-homie`, to match the repository name?

**Comment by qwandor** [comment]
Done the first three, up to you if you want to update the presentation.

**Comment by alsuren** [comment]
I think the presentation is still clear with the name "publisher" so I will leave it.
