### ISSUE TITLE
SOLVED: the topic for the device was corrupted and malformed

### ISSUE THREAD

**Issue by rabarar** [alsuren/mijia-homie#416]
I have a homie device sending messages to an mqtt broker,  but using the discover example, I see no events on Property change in the event loop. It matches but returns an empty vector of events.

looking at `lib.rs` in the `homie-controller` where the topic is subscribed appears to be the issue:

```
587     /// Start discovering Homie devices.
 588     async fn start(&self) -> Result<(), ClientError> {
 589         // Clear set of known devices so that we correctly subscribe to their topics again.
 590         *self.devices.lock().unwrap() = Arc::new(HashMap::new());
 591 
 592         //let topic = format!("{}/+/$homie", self.base_topic);
 593         let topic = format!("homie/#");
 594         log::trace!("Subscribe to {}", topic);
 595         self.mqtt_client.subscribe(topic, QoS::AtLeastOnce).await
 596     }   
 597     
```

if i modify the code to change the topic, i get messages.   if the topic is `homie/aurora-230202051/abc/entering-water-temperature`  why wouldn't `home` be the correct topic in the discovery example?

**Comment by rabarar** [comment]
here's a screenshot of the mqtt client showing the homie device subscription
![mqtt](https://github.com/alsuren/mijia-homie/assets/4433144/cef4ec5e-2358-43cd-9b17-7298e7795225)

**Comment by qwandor** [comment]
Hi, have you solved this yourself now or is there still an issue?

The discover example uses a base topic of `homie`, so it should be subscribing to `homie/+/$homie` to discover devices. Your device should be publishing `homie/aurora-230202051/$homie` with a value of `3.0` or whatever version it supports, so it should then be discovered and the controller will subscribe its topics.

**Comment by rabarar** [comment]
Hi It is solved. There was an update that malformed the homie topic string. Your subscription string is indeed correct and all’s well!Weird that the device dropped the $homie from the string, but an update cured the malformed topic.Thank you for asking and following up!Best,RobOn Nov 2, 2023, at 7:12 PM, Andrew Walbran ***@***.***> wrote:﻿
Hi, have you solved this yourself now or is there still an issue?
The discover example uses a base topic of homie, so it should be subscribing to homie/+/$homie to discover devices. Your device should be publishing homie/aurora-230202051/$homie with a value of 3.0 or whatever version it supports, so it should then be discovered and the controller will subscribe its topics.
