### ISSUE TITLE
Consider switching to from bluez-generated to https://github.com/i-poper/bluez-dbus

### ISSUE THREAD

**Issue by alsuren** [alsuren/mijia-homie#73]
* Try it out as a git dependency
* Ask the author to give it a license and publish it on crates.io
* Make the switch

**Comment by qwandor** [comment]
I filed https://github.com/i-poper/bluez-dbus/issues/1 asking for a license to be added, but didn't get any response.

**Comment by qwandor** [comment]
Shall we close this?
